### ISSUE TITLE
ImportError: libhts.so.2: cannot open shared object file

### ISSUE THREAD

**Issue by rohanpaul14855** [mlinderm/npsv2#2]
Hi I'm trying to run npsv2 with docker but I'm running into the following issue:
Apologies if this is a basic question, I'm new to docker
```
tf-docker /data > npsv2 command=preprocess     reference=hg38.fa     sequencer=HSXn     reads=align.bam     output=tests/results/stats.json
Traceback (most recent call last):
  File "/usr/local/bin/npsv2", line 33, in <module>
    sys.exit(load_entry_point('npsv2==0.1.0', 'console_scripts', 'npsv2')())
  File "/usr/local/bin/npsv2", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/npsv2-0.1.0-py3.8-linux-x86_64.egg/npsv2/main.py", line 7, in <module>
    from .simulation import bwa_index_loaded
  File "/usr/local/lib/python3.8/dist-packages/npsv2-0.1.0-py3.8-linux-x86_64.egg/npsv2/simulation.py", line 9, in <module>
    from . import _native
ImportError: libhts.so.2: cannot open shared object file: No such file or directory
```

I cloned npsv2 recursively, ran the following in my shell
```
docker run --entrypoint /bin/bash \
    -u $(id -u):$(id -g) \
    --shm-size=20g \
    -v "$tmpdir"/npsv_data:/data \
    -w /opt/npsv2 \
    -it \
    npsv2
```

Then in the docker shell, I ran
```
npsv2 command=preprocess \
    reference=hg38.fa \
    sequencer=HSXn \
    reads=align.bam \
    output=tests/results/stats.json \
    threads=32
 ```
 and got this error. Any suggestions?

**Comment by mlinderm** [comment]
Hi @rohanpaul14855! So far I am not able to recreate that error, at least running the demo preprocess command on an Intel-based Mac. It should be linking against a copy of `libhts.so` built as part of the seqlib library (a submodule within npsv2). Here is what I see locally:
```
root@83d926461cb3:/opt/npsv2# ldd /usr/local/lib/python3.8/dist-packages/npsv2-0.1.0-py3.8-li
nux-x86_64.egg/npsv2/_native.cpython-38-x86_64-linux-gnu.so 
        linux-vdso.so.1 (0x00007ffe0954d000)
        libhts.so.2 => /opt/npsv2/lib/seqlib/htslib/libhts.so.2 (0x00007f2ce6333000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f2ce6311000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f2ce612f000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2ce5fe0000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f2ce5fc5000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2ce5fa0000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2ce5dae000)
        libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007f2ce5d9b000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f2ce5d72000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f2ce6496000)
```
Did you observed any messages when building? I wonder if the included htslib didn't build but that didn't halt the overall build process.

**Comment by rohanpaul14855** [comment]
Thanks for looking into it. I tried building the docker image again and got a slightly different error but it seems related to seqlib. I get the following when I run `ldd`: `libhts.so.2 => not found`
```tf-docker /opt/npsv2 > ldd /usr/local/lib/python3.8/dist-packages/npsv2-0.1.0-py3.8-linux-x86_64.egg/npsv2/_native.cpython-38-x86_64-linux-gnu.so 
        linux-vdso.so.1 (0x00007ffcedfb0000)
        libhts.so.2 => not found
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fe7b1978000)
        libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007fe7b1965000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fe7b1783000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fe7b1634000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fe7b1617000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe7b15f4000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe7b1402000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fe7b1a4b000)
```
There are a couple of suspicious things in the build messages. One regarding seqlib is

```
/opt/npsv2/lib/seqlib/missing: Unknown --is-lightweight option
Try /opt/npsv2/lib/seqlib/missing --help for more information
configure: WARNING: 'missing' script is too old or missing
```
I have attached stdout after running `docker build` in case that's helpful
[npsv2.log](https://github.com/mlinderm/npsv2/files/14843725/npsv2.log)

**Comment by mlinderm** [comment]
@rohanpaul14855 I apologize for the delay (it was midterm season around here). I am still not sure what is causing your problem. In the meantime, I pushed some pre-built images for [linux/amd64](https://hub.docker.com/r/mlinderm0/npsv2) and [linux/arm64](https://hub.docker.com/r/mlinderm0/npsv2-m1).
